"""Firestore-backed persistence: animal upsert/dedup and per-source run
bookkeeping.

The application is stateless between Cloud Run Job executions except for
what is stored in Firestore. Four collections are used:

- animals:      one document per animal_key (dedup identity): animal_key,
                 animal_id, name, source, region, breed, description,
                 match_level, matched_term, weight, listing_url, first_seen,
                 last_seen, alert_sent, active.
- sightings:    one document per (animal_key, source) pair, doc id
                 f"{animal_key}__{source}", tracking per-source first/last
                 seen + the current listing URL/region.
- source_runs:  one auto-ID document per scraper run, recording success,
                 counts, and any error message.
- monitor_state: a single document (id "monitor") holding
                 last_successful_full_scan (ISO 8601 UTC), used to enforce
                 the 96-hour minimum interval between full shelter scans
                 (see main.is_scan_due) even though Cloud Scheduler may
                 invoke the job daily.

Firestore is schemaless, so there is no separate migration step: collections
and fields are created implicitly on first write. FirestoreStore itself
performs no I/O until first used, so constructing it is cheap/safe even if
credentials turn out to be invalid until the first call is made.

For unit tests, a `client` can be injected (see tests/fakes.py for a small
in-memory stand-in implementing the same get/set/update/document subset of
the real google-cloud-firestore API used here). Production code leaves
`client` unset and lets `google.cloud.firestore.Client()` pick up Application
Default Credentials (or the Firestore emulator, if FIRESTORE_EMULATOR_HOST is
set in the environment).
"""

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from .models import Animal, MatchLevel

logger = logging.getLogger(__name__)

ANIMALS_COLLECTION = "animals"
SIGHTINGS_COLLECTION = "sightings"
SOURCE_RUNS_COLLECTION = "source_runs"
MONITOR_STATE_COLLECTION = "monitor_state"
MONITOR_STATE_DOC_ID = "monitor"


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _level_value(level) -> str:
    return level.value if isinstance(level, MatchLevel) else str(level)


def _sighting_doc_id(animal_key: str, source: str) -> str:
    # animal_key and source are both generated by our own code and never
    # contain '/', which is the only character Firestore document IDs forbid.
    return f"{animal_key}__{source}"


class FirestoreStore:
    """Firestore-backed implementation of the animal dedup/alert-tracking
    rules: new matches are inserted with alert_sent=False; repeat sightings
    only refresh last_seen/description/url; alert_sent flips to True only
    after a confirmed successful email send (see main.py).
    """

    def __init__(self, client: Optional[Any] = None, project: Optional[str] = None, database: Optional[str] = None):
        if client is not None:
            self.client = client
        else:
            # Imported lazily so unit tests that always inject a fake client
            # never need the google-cloud-firestore package's network/auth
            # machinery to import cleanly.
            from google.cloud import firestore

            kwargs: Dict[str, Any] = {}
            if project:
                kwargs["project"] = project
            if database:
                kwargs["database"] = database
            self.client = firestore.Client(**kwargs)

    def close(self) -> None:
        close = getattr(self.client, "close", None)
        if callable(close):
            close()

    def _animals(self):
        return self.client.collection(ANIMALS_COLLECTION)

    def _sightings(self):
        return self.client.collection(SIGHTINGS_COLLECTION)

    def _source_runs(self):
        return self.client.collection(SOURCE_RUNS_COLLECTION)

    def get_animal(self, animal_key: str) -> Optional[Dict[str, Any]]:
        snap = self._animals().document(animal_key).get()
        return snap.to_dict() if snap.exists else None

    def upsert_animal(self, animal: Animal) -> bool:
        """Insert a new animal (alert_sent=False), or refresh last_seen/
        description/breed/weight for an existing one. Also records/updates
        a per-source sighting. Returns True if this animal_key is new.
        """
        now = _utcnow()
        doc_ref = self._animals().document(animal.animal_key)
        snap = doc_ref.get()

        if not snap.exists:
            doc_ref.set(
                {
                    "animal_key": animal.animal_key,
                    "animal_id": animal.animal_id,
                    "name": animal.name,
                    "source": animal.source,
                    "region": animal.region,
                    "breed": animal.breed_text,
                    "description": animal.description,
                    "match_level": _level_value(animal.match_level),
                    "matched_term": animal.matched_term,
                    "weight": animal.weight,
                    "listing_url": animal.url,
                    "first_seen": now,
                    "last_seen": now,
                    "alert_sent": False,
                    "active": True,
                }
            )
            is_new = True
        else:
            doc_ref.update(
                {
                    "description": animal.description,
                    "breed": animal.breed_text,
                    "weight": animal.weight,
                    "listing_url": animal.url,
                    "last_seen": now,
                    "active": True,
                }
            )
            is_new = False

        sighting_ref = self._sightings().document(_sighting_doc_id(animal.animal_key, animal.source))
        sighting_snap = sighting_ref.get()
        if sighting_snap.exists:
            sighting_ref.update({"last_seen": now, "url": animal.url, "region": animal.region})
        else:
            sighting_ref.set(
                {
                    "animal_key": animal.animal_key,
                    "source": animal.source,
                    "region": animal.region,
                    "url": animal.url,
                    "first_seen": now,
                    "last_seen": now,
                }
            )

        return is_new

    def should_alert(self, animal_key: str) -> bool:
        """True if this animal exists and has not yet had a successful alert
        sent for it (alert_sent is False)."""
        row = self.get_animal(animal_key)
        if row is None:
            return False
        return not bool(row.get("alert_sent", False))

    def mark_alert_sent(self, animal_key: str) -> None:
        self._animals().document(animal_key).update({"alert_sent": True})

    def start_source_run(self, source: str) -> str:
        doc_ref = self._source_runs().document()
        doc_ref.set(
            {
                "source": source,
                "started_at": _utcnow(),
                "completed_at": None,
                "success": None,
                "animals_scanned": 0,
                "matches_found": 0,
                "error_message": None,
            }
        )
        return doc_ref.id

    def finish_source_run(
        self,
        run_id: str,
        success: bool,
        animals_scanned: int = 0,
        matches_found: int = 0,
        error_message: Optional[str] = None,
    ) -> None:
        self._source_runs().document(run_id).update(
            {
                "completed_at": _utcnow(),
                "success": success,
                "animals_scanned": animals_scanned,
                "matches_found": matches_found,
                "error_message": error_message,
            }
        )

    def _monitor_state_ref(self):
        return self.client.collection(MONITOR_STATE_COLLECTION).document(MONITOR_STATE_DOC_ID)

    def get_last_successful_full_scan(self) -> Optional[datetime]:
        """Return the UTC timestamp of the last full scan that completed
        end-to-end (all sources attempted, matches processed), or None if a
        full scan has never completed successfully."""
        snap = self._monitor_state_ref().get()
        if not snap.exists:
            return None
        data = snap.to_dict() or {}
        raw = data.get("last_successful_full_scan")
        if not raw:
            return None
        return datetime.fromisoformat(raw)

    def update_last_successful_full_scan(self, when: Optional[datetime] = None) -> None:
        """Record that a full scan just completed successfully. Called once,
        after all sources have been attempted and alerts processed."""
        when = when or datetime.now(timezone.utc)
        self._monitor_state_ref().set(
            {"last_successful_full_scan": when.isoformat()}, merge=True
        )
